"""menu model added

Revision ID: 16457bc9fd28
Revises: 2f666672d3bd
Create Date: 2020-03-17 22:02:53.779386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16457bc9fd28'
down_revision = '2f666672d3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menu', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='unique')
    # ### end Alembic commands ###
