"""menu model relationship altered

Revision ID: 1927952bd283
Revises: 16457bc9fd28
Create Date: 2020-03-17 22:09:49.809009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1927952bd283'
down_revision = '16457bc9fd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_constraint('restaurant_restaurant_menu_fkey', 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'restaurant_menu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('restaurant_menu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurant_restaurant_menu_fkey', 'restaurant', 'menu', ['restaurant_menu'], ['id'])
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'restaurant_id')
    # ### end Alembic commands ###
