"""added menu table

Revision ID: 2f666672d3bd
Revises: fe44a0fa1a31
Create Date: 2020-03-16 22:44:30.151484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f666672d3bd'
down_revision = 'fe44a0fa1a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_pic', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('restaurant', sa.Column('restaurant_menu', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'menu', ['restaurant_menu'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'restaurant_menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
