"""reservation table added

Revision ID: 4097a9b9fb41
Revises: d1caab79fafb
Create Date: 2020-04-09 17:24:28.614806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4097a9b9fb41'
down_revision = 'd1caab79fafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_code', sa.String(length=128), nullable=False),
    sa.Column('no_of_persons', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('reservee', sa.Integer(), nullable=True),
    sa.Column('reservation_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_to'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['reservee'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
