"""initial database migration

Revision ID: a99376149d2b
Revises: 
Create Date: 2021-09-03 09:59:31.804449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99376149d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('profile_image2', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=11), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_image', sa.String(length=255), nullable=True),
    sa.Column('restaurant_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('restaurant_thumbnail2', sa.String(length=255), nullable=True),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_type', sa.String(length=75), nullable=False),
    sa.Column('location', sa.String(length=155), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('opening_day', sa.String(length=55), nullable=True),
    sa.Column('closing_day', sa.String(length=55), nullable=True),
    sa.Column('opening_time', sa.String(length=15), nullable=False),
    sa.Column('closing_time', sa.String(length=15), nullable=False),
    sa.Column('no_of_vacancies', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=11), nullable=False),
    sa.Column('telephone_number', sa.String(length=8), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_name')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_image', sa.String(length=255), nullable=True),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.String(length=10), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('num_of_persons', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.String(length=10), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('customer_email', sa.String(length=75), nullable=True),
    sa.Column('customer_contact_number', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('menu')
    op.drop_table('restaurants')
    op.drop_table('users')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
