"""item is_sol_out column removed

Revision ID: b12c719862da
Revises: 4cc364993009
Create Date: 2021-01-17 00:26:23.441315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12c719862da'
down_revision = '4cc364993009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_sold_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_sold_out', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
