"""comment column added

Revision ID: b6447121cf1f
Revises: 147cf7ff8ecd
Create Date: 2020-04-15 15:59:17.564861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6447121cf1f'
down_revision = '147cf7ff8ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###
