"""updated user table

Revision ID: e526ad864f45
Revises: 8f302869156d
Create Date: 2019-11-29 00:58:08.342735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e526ad864f45'
down_revision = '8f302869156d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('user_type', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['fullname'])
    op.drop_column('user', 'owner')
    op.drop_column('user', 'customer')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('customer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('owner', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
