"""updated user table

Revision ID: e7096ee09464
Revises: e526ad864f45
Create Date: 2019-11-29 01:00:37.837154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7096ee09464'
down_revision = 'e526ad864f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.drop_constraint('user_fullname_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['full_name'])
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_fullname_key', 'user', ['fullname'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
