"""added restaurant owner id on reservation table

Revision ID: fea2707417ea
Revises: d01c7cccec0d
Create Date: 2021-12-20 13:07:24.152721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea2707417ea'
down_revision = 'd01c7cccec0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('restaurant_owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'restaurant_owner_id')
    # ### end Alembic commands ###
